version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:jammy
    steps:
      - checkout

      - run:
          name: Configure LLVM
          command: apt-get update -y && apt-get install lsb-release wget software-properties-common gnupg cmake ninja-build gcc -y && echo -ne '\n' | bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

      - run:
          name: Build
          command: mkdir build && cd build && cmake -G Ninja .. && ninja
          environment:
            CXX: clang++-15

      - run:
          name: Test
          command: cd build && ctest -V