version: 2.1

jobs:
  build:
    docker:
      - image: ademr0/llvm:latest
    steps:
      - checkout
      - run:
          name: Build
          command: mkdir build && cd build && cmake .. && make
